services:
  db:
    container_name: teste_db
    image: mariadb:lts
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=meu_sistema
      - MARIADB_USER=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - teste_network

  php:
    container_name: teste_php
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html 
    depends_on:
      - db
    networks:
      - teste_network
    ports:
      - "8080:80"   

  phpmyadmin:
    container_name: teste_phpmyadmin
    image: phpmyadmin:5.2.2
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8081:80" # seu app php vai rodar em http://localhost:8081
    depends_on:
      - db
    networks:
      - teste_network

networks:
  teste_network:
    driver: bridge
    attachable: true

volumes:
  dbdata:
    name: 'testdata'